services:
  selenium:
    container_name: selenium
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.selenium
    image: selenium-test-runner:latest
    working_dir: /app
    volumes:
      - selenium_src:/app
      - ~/.m2:/root/.m2
    environment:
      SUITE: LoginRunner
      BROWSER: chrome
    networks:
      - project-network

volumes:
  selenium_src:
    external: true

networks:
  project-network:
    external: true