services:
  cypress:
    container_name: selenium
    image: selenium
    build:
      context: . 
      dockerfile: ./dockerfiles/Dockerfile.selenium
    working_dir: /app
    volumes:
      - selenium_src:/app
    environment:
      RUNNER: loginUserSuite
      BROWSER: chrome
    networks:
      - project-network

volumes:
  selenium_src:
    name: selenium_src
    external: true

networks:
  project-network:
    external: true
