services:
  selenium:
    container_name: selenium
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.selenium
    image: selenium-test-runner:latest
    working_dir: /app
    volumes:
      - selenium_src:/app
      - ~/.m2:/root/.m2
    environment:
        SUITE: ${SUITE}
        BROWSER: ${BROWSER}
        HEADLESS: ${HEADLESS:-true}
        WITHOUT_CERTS: ${WITHOUT_CERTS:-true}
    entrypoint: >
      bash -c "
        xvfb-run -a mvn clean verify -Dtest=$${SUITE}
      "
    networks:
      - project-network

volumes:
  selenium_src:
    external: true

networks:
  project-network:
    external: true