FROM maven:3.9.6-eclipse-temurin-11

USER root

# 1. Ensure that mvn is in the PATH
ENV MAVEN_HOME=/usr/share/maven \
    MAVEN_CONFIG=/root/.m2 \
    PATH=${MAVEN_HOME}/bin:${PATH}

# 2. Install basic dependencies for UI tests
RUN apt-get update && apt-get install -y --no-install-recommends \
      wget \
      curl \
      gnupg \
      unzip \
      software-properties-common \
      xvfb \
      libxi6 \
      libgconf-2-4 \
      libnss3 \
      libxss1 \
      libappindicator1 \
      fonts-liberation \
      libatk-bridge2.0-0 \
      libgtk-3-0 \
      ca-certificates \
      dbus-x11 \
      libasound2 \
    && rm -rf /var/lib/apt/lists/*

# ------------------------------------
# 3. Install Firefox and geckodriver
# ------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
      firefox \
      libdbus-glib-1-2 \
      libxt6 \
      libx11-xcb1 \
      libxcomposite1 \
      libxdamage1 \
      libxrandr2 \
      libpango-1.0-0 \
      libatk-bridge2.0-0 \
      libgtk-3-0 \
      libcups2 \
      libxss1 \
      libdrm2 \
      libxshmfence1 \
      libxfixes3 \
      libnss3 \
      fonts-liberation \
      libappindicator3-1 \
      xdg-utils \
    && rm -rf /var/lib/apt/lists/*

# Install geckodriver
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz \
    && tar -xvzf geckodriver-v0.30.0-linux64.tar.gz \
    && mv geckodriver /usr/local/bin/

# ------------------------------------
# 4. Install Microsoft Edge
# ------------------------------------
RUN curl https://packages.microsoft.com/keys/microsoft.asc \
      | gpg --dearmor > microsoft.gpg \
    && install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/ \
    && echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" \
      > /etc/apt/sources.list.d/microsoft-edge.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends microsoft-edge-stable \
    && rm microsoft.gpg \
    && rm -rf /var/lib/apt/lists/*

# ------------------------------------
# 5 Install Google Chrome
# ------------------------------------
RUN curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && \
    apt-get install -y google-chrome-stable && \
    rm -rf /var/lib/apt/lists/*

# 6. Verify that mvn is present
RUN mvn --version

# 7. Create the selenium user
RUN useradd -m selenium

# 8. Change Permissions to working directory
WORKDIR /app
COPY pom.xml /app/
RUN mvn clean
RUN chown -R selenium:selenium /app
RUN chmod -R 777 /app

# Change to the selenium user
USER selenium
